config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :planets, only: [:index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :destroy]
  namespace :owner do
    resources :planets, only: [:index]
    resources :bookings, only: [:index] do
      member do
        patch :accept
        patch :decline
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :planet
  belongs_to :user
  validates :departure_date, :arrival_date, presence: true
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  has_many :bookings, dependent: :nullify
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :planets, dependent: :destroy
  has_many :bookings, dependent: :nullify
  has_many :owner_bookings, through: :planets, source: :bookings
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    # @bookings = Booking.all
    @bookings = current_user.bookings.order(updated_at: :desc)
  end

  def create
    @planet = Planet.find(params[:planet_id])
    @booking = Booking.new(booking_params)
    @booking.planet = @planet
    @booking.user = current_user

    if @booking.valid?
      @booking.total_price = (@booking.departure_date - @booking.arrival_date) * @booking.planet.price_per_millenia
      @booking.save
      redirect_to bookings_path(@booking)
    else
      render "planets/show", status: :unprocessable_entity
    end
  end

  def rate
  end

  def destroy
    @bookings.delete
  end

  private

  def booking_params
    params.require(:booking).permit(:arrival_date, :departure_date)
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def index
    @bookings = current_user.owner_bookings.order(updated_at: :desc)

  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    @booking.save
    redirect_to owner_bookings_path
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.status = "declined"
    @booking.save
    redirect_to owner_bookings_path
  end
end

app/controllers/owner/planets_controller.rb
class Owner::PlanetsController < ApplicationController
  def index
    @planets = current_user.planets
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @planets = Planet.last(4)
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def show
    @planet = Planet.find(params[:id])
    @booking = Booking.new
  end

  def new
    @planet = Planet.new
  end

  def create
    @planet = Planet.new(planet_params)
    @planet.owner = current_user
    if @planet.save
      redirect_to planet_path(@planet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @planets = Planet.all
    @markers = @planets.geocoded.map do |planet|
      {
        lat: planet.latitude,
        lng: planet.longitude,
        image_url: helpers.asset_url("rocket-solid.svg")
      }
    end
  end

  def edit
  end

  def update
  end

  def ask
  end

  private

  def planet_params
    params.require(:planet).permit(:name, :address, :capacity, :description, :price_per_millenia, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="background-img">
  <div class="container">
    <h2>My bookings</h2>
    <div class="row">
      <% @bookings.each do |booking|%>
        <div class="justify-content-center p-3">
          <div class="card-product">
            <%= cl_image_tag booking.planet.photo.key%>
            <div class="card-product-infos d-flex align-items-center justify-content-between">
              <div>
                <h2 class="title-planet"><%= booking.planet.name %>&nbsp;</h2>
                <p><i class="fa-solid fa-user mt-2"></i>  Booked by <%= booking.user.name %></p>
                <p><i class="fa-regular fa-calendar-days mt-2"></i>  From <%= booking.arrival_date.ordinalize %> to <%= booking.departure_date.ordinalize %> millenium</p>
              </div>
              <h2 class="total-price"><%= booking.total_price %><%= image_tag "ico.png" %></h2>
              <div>
                <% if booking.status=="declined" %>
                  <div class="booking_button_decline">
                    <i class="fa-solid fa-circle-xmark"></i>
                  </div>
                <% elsif booking.status=="pending" %>
                  <div class="booking_button_pending">
                    <i class="fa-solid fa-clock"></i>
                  </div>
                <% elsif booking.status=="accepted" %>
                  <div class="booking_button_accept">
                    <i class="fa-solid fa-circle-check"></i>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingPlanet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/alert" %>
  </body>
</html>

app/views/owner/bookings/index.html.erb
<div class="background-img">
  <div class="container">
    <h2>Booked planets</h2>
    <div class="row">
      <% @bookings.each do |booking|%>
        <div class="justify-content-center p-3">
          <div class="card-product">
            <%= cl_image_tag booking.planet.photo.key%>
            <div class="card-product-infos d-flex align-items-center justify-content-between">
              <div>
                <h2 class="title-planet"><%= booking.planet.name %>&nbsp;</h2>
                <p><i class="fa-solid fa-user mt-2"></i>  Booked by <%= booking.user.name %></p>
                <p><i class="fa-regular fa-calendar-days mt-2"></i>  From <%= booking.arrival_date.ordinalize %> to <%= booking.departure_date.ordinalize %> millenium</p>
              </div>
              <h2 class="total-price"><%= booking.total_price %><%= image_tag "ico.png" %></h2>
              <div>
                <% if booking.status=="pending" %>
                  <div class="btn-accepte-decline">
                    <p><%= link_to 'Accept', accept_owner_booking_path(booking), data: { 'turbo-method': :patch }, :class => "btn btn-success" %></p>
                    <p><%= link_to 'Decline', decline_owner_booking_path(booking), data: { 'turbo-method': :patch }, :class => "btn btn-danger" %></p>
                  </div>
                <% elsif booking.status=="declined" %>
                  <div class="booking_tag_decline">
                    <i class="fa-solid fa-circle-xmark"></i>
                  </div>
                <% elsif booking.status=="accepted" %>
                  <div class="booking_tag_accept">
                    <i class="fa-solid fa-circle-check"></i>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/owner/planets/index.html.erb
<div class="background-img">
  <div class="container">
    <h2 class="title-index">My planets</h2>
    <div class="row" >
      <% @planets.each do |planet|%>
        <div class="col-3 d-flex justify-content-center">
          <div class="card-trip">
            <%= link_to planet_path(planet), class:"text-decoration-none text-white" do %>
              <%= cl_image_tag planet.photo.key, height: 300, width: 300, crop: :fill %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= planet.name %></h2>
                </div>
                <div class="info-index">
                  <p><%= planet.capacity %> billion people</p>
                  <div class="d-flex align-items-center">
                    <p><%= planet.price_per_millenia %>&nbsp;<p>
                    <%= image_tag "ico.png" %>
                    <p>/millennium</p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/pages/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container container-fluid">
    <%= link_to "#", class: "navbar-brand d-flex flex-row" do %>
      <%= image_tag "logo.png" %>
      <h1>Planetarium.io</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="landing-picture">
  <div class="landing-bookingplanet container">
    <h1 class="landing-title booking">Book...</h1>
    <h1 class="landing-title aplanet">...a planet</h1>
    <div class="button-search">
      <%= link_to "Explore the univers !",  planets_path , class: "btn btn-primary btn-home mx-auto rounded" %>
      <%= image_tag "arrow.png", height: '24', width: '80' %>
    </div>
  </div>
  <div class="container">
    <h2 class="trending-title">Latest planets :</h2>
      <div class="row">
        <% @planets.each do |planet|%>
        <div class="col-3 d-flex justify-content-center">
          <div class="card-trip">
            <%= link_to planet_path(planet), class:"text-decoration-none text-white" do %>
              <%= cl_image_tag planet.photo.key, height: 300, width: 300, crop: :fill %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= planet.name %></h2>
                </div>
                <div class="info-index">
                  <p><%= planet.capacity %> billion people</p>
                  <div class="d-flex align-items-center">
                    <p><%= planet.price_per_millenia %>&nbsp;<p>
                    <%= image_tag "ico.png" %>
                    <p>/millennium</p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <%end%>
      </div>
  </div>

app/views/planets/index.html.erb
<div class="background-img">
  <div class="container">
    <h2 class="title-index">All planets</h2>
    <div class="row" >
      <div class="col-6 row">
        <% @planets.each do |planet|%>
          <div class="col-6 d-flex justify-content-center">
            <div class="card-trip">
              <%= link_to planet_path(planet), class:"text-decoration-none text-white" do %>
                <%= cl_image_tag planet.photo.key, height: 300, width: 300, crop: :fill %>
                <div class="card-trip-infos">
                  <div>
                    <h2><%= planet.name %></h2>
                  </div>
                  <div class="info-index">
                    <p><%= planet.capacity %> billion people</p>
                    <div class="d-flex align-items-center">
                      <p><%= planet.price_per_millenia %>&nbsp;<p>
                      <%= image_tag "ico.png" %>
                      <p>/millennium</p>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <%end%>
      </div>
      <div class="col-6">
        <div class="map">
          <div style="width: 100%; height: 600px;"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/planets/new.html.erb
<div class="background-img">
  <div class="container d-flex new-form">
    <div class="row">
      <div class="col-sm d-flex justify-content-center">
        <div class="rounded p-3">
          <h3 class="text-center">Create your planet</h3>
          <%= simple_form_for @planet do |f| %>
            <%= f.input :name %>
            <%= f.input :address, label: "Location" %>
            <%= f.input :capacity, label: "Capacity in billion" %>
            <%= f.input :description %>
            <%= f.input :price_per_millenia, label: "Price per millenium" %>
            <%= f.input :photo, as: :file, label: "Picture", defaults: "test" %>
            <div class="d-flex text-center justify-content-around p-2">
              <%= f.submit "Create !",class: 'btn btn-primary' %>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/planets/show.html.erb
 <div class="background-img">
  <div class="container center-show">
    <%= link_to "< Explore",  planets_path , class: "btn-show" %>
    <div class="w-100">
      <div class="title-show">
        <h1><%= @planet.name %></h1>
        <h4><%= @planet.capacity %> billion people</h4>
        <div class="d-flex align-items-center">
          <h4><%= @planet.price_per_millenia %>&nbsp;<h4>
          <%= image_tag "ico.png" %>
          <h4>/millennium</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-8 card-planet d-flex justify-content-center">
          <div class="planet-owner">
            <%= cl_image_tag @planet.photo.key, height: 300, width: 300, crop: :fill, class:"planet-img" %>
            <%= cl_image_tag @planet.owner.photo.key, class:"avatar-show", "data-bs-toggle": "tooltip",  "data-bs-placement": "top", title: @planet.owner.name  %>
          </div>
          <div class="description w-100">
            <p><%= @planet.description %></p>
          </div>
        </div>
        <% unless @planet.owner == current_user %>
          <div class="col-4 text-center">
            <h1>Book this planet</h1>
            <%= simple_form_for [@planet, @booking] do |f| %>
              <%= f.input :arrival_date, label:"Arrival date in millenia", placeholder:"3" %>
              <%= f.input :departure_date, label:"Departure date in millenia", placeholder:"4" %>
              <%= f.submit "Book this planet", class: "btn btn-primary" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_alert.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container container-fluid position-relative">
    <%= link_to root_path, class: "navbar-brand d-flex flex-row" do %>
      <%= image_tag "favicon.png" %>
      <h1>Planetarium.io</h1>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%= link_to "Create a planet", new_planet_path, class: "btn btn-primary nav-btn" %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% if current_user.planets.any? %>
                <%= link_to "My planets", owner_planets_path, class: "nav-link" %>
            <% end %>
            <% if current_user.bookings.any? %>
                <%= link_to "My bookings", bookings_path, class: "nav-link" %>
            <% end %>
            <% if current_user.owner_bookings.any? %>
                <%= link_to "Booked planets", owner_bookings_path, class: "nav-link" %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, class: "nav-link", data: {turbo_method: :delete} %>
          </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link login-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>